### ISSUE TITLE
defaultHeight is not applied

### ISSUE THREAD

**Issue by mlb5000** [eviltrout/ember-cloaking#11]
You can update the `cloak` function to this to get defaultHeight to apply:

    /**
      Removes the view from the DOM and tears down all observers.

      @method cloak
    */
    cloak: function() {
      var containedView = this.get('containedView'),
          self = this;

      if (containedView && this.get('state') === 'inDOM') {
        var theHeight = this.get('defaultHeight');
        if (theHeight === undefined) {
          theHeight = this.$().height();
        }
        var style = 'height: ' + theHeight + 'px;';
        this.set('style', style);
        this.$().prop('style', style);

        // We need to remove the container after the height of the element has taken
        // effect.
        Ember.run.schedule('afterRender', function() {
          self.set('containedView', null);
          containedView.willDestroyElement();
          containedView.remove();
        });
      }
    },

**Comment by runspired** [comment]
@eviltrout I believe we can also close this one with the changes in #15

**Comment by eviltrout** [comment]
Sure, also thanks for working on this!
