### ISSUE TITLE
Using dynamic child views

### ISSUE THREAD

**Issue by g-cassie** [eviltrout/ember-cloaking#22]
I managed to implement this with dynamic child views.  I thought I would post my solution to see if I am doing it right.  If I am, maybe it would make sense to add this to the docs?
````javascript
var MyCollectionView = Ember.CloakedCollectionView.extend({
  createChildView: function(viewClass, attrs){
    var obj = attrs['content'],
          idProperty = this.get('idProperty'),
          uncloakDefault = !!this.get('uncloakDefault'),
          cloakView;

    if (obj.get('constructor.typeKey') === 'category'){
      cloakView = MyCategoryView;
    }
    else if (obj.get('constructor.typeKey') === 'item'){
      cloakView = MyItemView;
    }
 
    viewClass = Ember.CloakedView.extend({
      classNames: ['my-collection-cloak'],
      cloaks: cloakView,
      preservesContext: this.get('preservesContext') === "true",
      defaultHeight: this.get('defaultHeight'),

      init: function() {
        this._super();
        if (idProperty) {
            this.set('elementId', cloakView + '-cloak-' + this.get('content.' + idProperty));
        }
        this.uncloak();
          if (uncloakDefault) {
            this.uncloak();
          } else {
            this.cloak();
          }
      }
    });

    return this._super(viewClass, attrs);
  }
````

**Comment by tschoartschi** [comment]
This seems to be somehow what I'm looking for. I also have a long list of items which belong to a category. In my handlebar file I do the following:

```handlebars
{{#each tag in elements}}
    ....
    ....        
    {{#each item in tag.sortedItems}}
        ....
        ....
    {{/each}}
{{/each}}
```
 
Could your solution be applied to my case? If yes, could you explain your solution in more detail? Because I don't fully understand it. Thanks in advance :smile:

**Comment by runspired** [comment]
@tschoartschi the solution by @g-cassie is for rendering different views based on the type of child, not for displaying a nested lists.  In your case, you would cloak the tag list and all the items for a tag would be cloaked or uncloaked at once, which is still an improvement but not as good as you seem to be looking for.

I can see a way to add nested list functionality to cloaking, but it would require a major rewrite.  I may start a new addon based on the es6 branch that does this allowing one level deep with the intention of allowing cloaked `select`-like components that contain `groups`.

**Comment by g-cassie** [comment]
@tschoartschi you might be able to get benefit from my approach if you write a computed array to compound your nested arrays into a single flat array (e.g. `[<Tag Instance>, <Item Instance>, <Item Instance>, <Tag Instance>, etc.]`) Then you can use dynamic child views to display a different component for an ItemInstance than for a TagInstance.  

For the record I am not actually using ember-cloaking in my project anymore and I think my sample code above may have had some bugs.  Sorry I can't be of more assistance.
