### ISSUE TITLE
Stop rendering ALL cloaked views

### ISSUE THREAD

**Issue by H1D** [eviltrout/ember-cloaking#9]
It turned out that `ember-cloakning` uncloaks **all** views first and only then cloaks it back :expressionless: 

Demo http://jsbin.com/ACikukuCA/35/edit (check out console)

Is it by design?

We can change [this line](https://github.com/eviltrout/ember-cloaking/blob/master/ember-cloaking.js#L197) to `this.cloak()` but it's half-measure. Some kind of progressive rendering should be implemented which would check what's on screen after each view uncloaked.

**Comment by runspired** [comment]
@eviltrout I believe we can close this: https://github.com/eviltrout/ember-cloaking/pull/15
